apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "videocms.fullname" . }}
  labels:
    {{- include "videocms.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "videocms.name" . }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "videocms.name" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: videocms
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "videocms.fullname" . }}
            - secretRef:
                name: {{ include "videocms.fullname" . }}
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "videocms.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
