apiVersion: v1
kind: Secret
metadata:
  name: {{ include "videocms.fullname" . }}
  labels:
    {{- include "videocms.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.env.JWT_SECRET | quote }}
  ADMIN_PASSWORD: {{ .Values.env.ADMIN_PASSWORD | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
